import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { prismaClient } from "@/lib/prisma";

import UserProvider from "@/components/providers/User";
import { getCurrent as getCurrentUser } from "@/models/User";

const prisma = prismaClient();

const mainSerif = localFont({
  src: "./fonts/Piazzolla-V.ttf",
  variable: "--font-main-serif",
  weight: "100 900",
});
const mainSans = localFont({
  src: "./fonts/Montserrat-V.ttf",
  variable: "--font-main-sans",
  weight: "100 900",
});
const mainMono = localFont({
  src: "./fonts/SourceCodePro-V.ttf",
  variable: "--font-main-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body
        className={`${mainSans.variable} ${mainMono.variable} ${mainSerif.variable} antialiased font-[family-name:var(--font-main-sans)] layout-body`}
      >
        <UserProvider user={user}>
          <div className="container mx-auto  h-[100dvh] layout-container">
            {children}
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
